print ("welcome to robo barista cafe",)
name = input ("what is your name")
print ("hello", name, "what do you want to order")
menu = input ("we've java coffee, coffee with milk and normal coffee what do you want to order")
print ("okay mr", name, "we'll have that", menu, "ready for you in a comment") 